behaviors:
  AR4Robot:
    trainer_type: ppo

    hyperparameters:
      # Common PPO/SAC hyperparameters
      batch_size: 256
      buffer_size: 2560
      learning_rate: 3.0e-4
      learning_rate_schedule: linear

      # PPO-specific hyperparameters
      beta: 5.0e-3
      beta_schedule: constant
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3
      shared_critic: false

    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple

      memory:
        sequence_length: 256
        memory_size: 256

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99

    # Trainer settings
    max_steps: 1.0e6
    time_horizon: 64
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 10000
    threaded: true
