"""
Tests for OperationIndexer.refresh_index()
==========================================

Covers:
- Empty store: all current operations are added
- Pre-populated store: already-indexed IDs are skipped
- Returns the same store object (mutates in place)
- No-op when all IDs already present: no embeddings generated, store unchanged
- Saves to disk when save=True and RAG_AUTO_SAVE_INDEX=True
- Does not save when save=False
- Preserves existing metadata on already-indexed entries
- Context documents (workspace_layout etc.) skipped if already indexed
- New operations added after a prior full index are picked up by refresh

All network calls (EmbeddingGenerator, OperationRegistry) are mocked.
"""

import numpy as np
import pytest
from unittest.mock import MagicMock, patch, call

from rag.VectorStore import VectorStore
from rag.Indexer import OperationIndexer


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _unit(n: int) -> np.ndarray:
    """Return a normalised unit vector of length n along axis 0."""
    v = np.zeros(n)
    v[0] = 1.0
    return v


def _make_mock_op(op_id: str, name: str, dim: int = 4):
    """Build a mock BasicOperation that satisfies the indexer's interface."""
    op = MagicMock()
    op.operation_id = op_id
    op.name = name
    op.category = MagicMock(value="navigation")
    op.complexity = MagicMock(value="basic")
    op.description = f"Test operation {name}"
    op.average_duration_ms = 500.0
    op.success_rate = 0.9
    op.parameters = []
    op.to_rag_document = MagicMock(return_value=f"doc for {name}")
    return op


def _make_mock_workflow(pat_id: str, name: str):
    """Build a mock WorkflowPattern that satisfies the indexer's interface."""
    wf = MagicMock()
    wf.pattern_id = pat_id
    wf.name = name
    wf.category = MagicMock(value="navigation")
    wf.description = f"Test workflow {name}"
    wf.steps = [MagicMock(), MagicMock()]
    wf.to_rag_document = MagicMock(return_value=f"doc for workflow {name}")
    return wf


def _make_indexer(ops, workflows=None, embedding_dim: int = 4):
    """
    Build an OperationIndexer with fully mocked registry and embedding generator.

    The embedding generator returns deterministic unit vectors scaled by index.
    """
    registry = MagicMock()
    registry.get_all_operations.return_value = ops

    workflow_registry = MagicMock()
    workflow_registry.get_all_patterns.return_value = workflows or []

    embedding_gen = MagicMock()
    call_count = [0]

    def fake_generate(texts):
        # Return one unit vector per text, each with a unique small offset
        result = []
        for _ in texts:
            v = _unit(embedding_dim).copy()
            v[1] = call_count[0] * 0.001
            call_count[0] += 1
            result.append(v)
        return result

    embedding_gen.generate_embeddings.side_effect = fake_generate

    indexer = OperationIndexer(
        registry=registry,
        workflow_registry=workflow_registry,
        embedding_generator=embedding_gen,
    )
    return indexer, embedding_gen


# The 4 context document IDs generated by _get_multi_robot_context_documents
CONTEXT_DOC_IDS = {
    "context_workspace_layout",
    "context_coordination_patterns",
    "context_safety_constraints",
    "context_parallel_execution",
}


# ---------------------------------------------------------------------------
# Empty-store behaviour
# ---------------------------------------------------------------------------

class TestRefreshIndexEmptyStore:
    """When the store is empty, refresh_index adds all current documents."""

    def test_all_operations_added_to_empty_store(self):
        """refresh_index on an empty store adds all registry operations."""
        ops = [_make_mock_op("op_001", "move_to_coordinate")]
        indexer, _ = _make_indexer(ops)

        store = VectorStore()
        result = indexer.refresh_index(store, save=False)

        # op + 4 context docs = 5 minimum entries
        assert "op_001" in result.operation_ids

    def test_context_docs_added_to_empty_store(self):
        """refresh_index on an empty store also adds context documents."""
        ops = [_make_mock_op("op_001", "move_to_coordinate")]
        indexer, _ = _make_indexer(ops)

        store = VectorStore()
        result = indexer.refresh_index(store, save=False)

        for ctx_id in CONTEXT_DOC_IDS:
            assert ctx_id in result.operation_ids, f"Missing context doc: {ctx_id}"

    def test_embeddings_generated_for_all_new_docs(self):
        """generate_embeddings is called once with all new document texts."""
        ops = [_make_mock_op("op_001", "move_to_coordinate")]
        indexer, emb_gen = _make_indexer(ops)

        store = VectorStore()
        indexer.refresh_index(store, save=False)

        assert emb_gen.generate_embeddings.call_count == 1
        texts = emb_gen.generate_embeddings.call_args[0][0]
        # 1 op + 4 context docs
        assert len(texts) == 1 + len(CONTEXT_DOC_IDS)


# ---------------------------------------------------------------------------
# Skip already-indexed IDs
# ---------------------------------------------------------------------------

class TestRefreshIndexSkipsExisting:
    """refresh_index skips operations already present in the store."""

    def test_already_indexed_op_not_re_added(self):
        """An operation already in the store is not duplicated."""
        ops = [_make_mock_op("op_001", "move_to_coordinate")]
        indexer, _ = _make_indexer(ops)

        store = VectorStore()
        store.add_operation("op_001", _unit(4), {"name": "move_to_coordinate"})

        indexer.refresh_index(store, save=False)

        assert store.operation_ids.count("op_001") == 1

    def test_already_indexed_context_docs_not_re_added(self):
        """Context documents already in the store are not duplicated."""
        ops = [_make_mock_op("op_001", "move_to_coordinate")]
        indexer, _ = _make_indexer(ops)

        store = VectorStore()
        for ctx_id in CONTEXT_DOC_IDS:
            store.add_operation(ctx_id, _unit(4), {"name": ctx_id})

        indexer.refresh_index(store, save=False)

        for ctx_id in CONTEXT_DOC_IDS:
            assert store.operation_ids.count(ctx_id) == 1

    def test_no_embeddings_generated_when_all_indexed(self):
        """generate_embeddings is never called when nothing is new."""
        ops = [_make_mock_op("op_001", "move_to_coordinate")]
        indexer, emb_gen = _make_indexer(ops)

        # Pre-populate store with every expected document
        store = VectorStore()
        store.add_operation("op_001", _unit(4), {"name": "move_to_coordinate"})
        for ctx_id in CONTEXT_DOC_IDS:
            store.add_operation(ctx_id, _unit(4), {"name": ctx_id})

        indexer.refresh_index(store, save=False)

        emb_gen.generate_embeddings.assert_not_called()

    def test_only_new_ops_get_embeddings(self):
        """When one of two operations is already indexed, only the new one is embedded."""
        ops = [
            _make_mock_op("op_001", "move_to_coordinate"),
            _make_mock_op("op_002", "grasp_object"),
        ]
        indexer, emb_gen = _make_indexer(ops)

        store = VectorStore()
        # Pre-index op_001 and all context docs
        store.add_operation("op_001", _unit(4), {"name": "move_to_coordinate"})
        for ctx_id in CONTEXT_DOC_IDS:
            store.add_operation(ctx_id, _unit(4), {"name": ctx_id})

        indexer.refresh_index(store, save=False)

        # Only op_002 doc should have been embedded
        assert emb_gen.generate_embeddings.call_count == 1
        texts = emb_gen.generate_embeddings.call_args[0][0]
        assert len(texts) == 1


# ---------------------------------------------------------------------------
# Returns same store object
# ---------------------------------------------------------------------------

class TestRefreshIndexReturnValue:
    """refresh_index returns the same VectorStore instance that was passed in."""

    def test_returns_same_store_object(self):
        """refresh_index must mutate and return the passed-in store, not create a new one."""
        ops = [_make_mock_op("op_001", "move_to_coordinate")]
        indexer, _ = _make_indexer(ops)

        store = VectorStore()
        result = indexer.refresh_index(store, save=False)

        assert result is store

    def test_returned_store_has_new_entries(self):
        """The returned store contains the newly added operations."""
        ops = [_make_mock_op("op_001", "move_to_coordinate")]
        indexer, _ = _make_indexer(ops)

        store = VectorStore()
        result = indexer.refresh_index(store, save=False)

        assert "op_001" in result.operation_ids


# ---------------------------------------------------------------------------
# Persistence (save/no-save)
# ---------------------------------------------------------------------------

class TestRefreshIndexSave:
    """refresh_index respects the save= parameter and RAG_AUTO_SAVE_INDEX config."""

    def test_save_true_calls_store_save(self):
        """save=True triggers VectorStore.save() when RAG_AUTO_SAVE_INDEX is True."""
        ops = [_make_mock_op("op_001", "move_to_coordinate")]
        indexer, _ = _make_indexer(ops)
        store = VectorStore()

        with patch("rag.Indexer.RAG_AUTO_SAVE_INDEX", True), \
             patch.object(store, "save") as mock_save:
            indexer.refresh_index(store, save=True)

        mock_save.assert_called_once()

    def test_save_false_does_not_call_store_save(self):
        """save=False must never call VectorStore.save()."""
        ops = [_make_mock_op("op_001", "move_to_coordinate")]
        indexer, _ = _make_indexer(ops)
        store = VectorStore()

        with patch("rag.Indexer.RAG_AUTO_SAVE_INDEX", True), \
             patch.object(store, "save") as mock_save:
            indexer.refresh_index(store, save=False)

        mock_save.assert_not_called()

    def test_auto_save_false_prevents_save(self):
        """When RAG_AUTO_SAVE_INDEX=False, save is not called even with save=True."""
        ops = [_make_mock_op("op_001", "move_to_coordinate")]
        indexer, _ = _make_indexer(ops)
        store = VectorStore()

        with patch("rag.Indexer.RAG_AUTO_SAVE_INDEX", False), \
             patch.object(store, "save") as mock_save:
            indexer.refresh_index(store, save=True)

        mock_save.assert_not_called()


# ---------------------------------------------------------------------------
# Metadata preservation
# ---------------------------------------------------------------------------

class TestRefreshIndexMetadataPreservation:
    """refresh_index must not overwrite metadata on existing entries."""

    def test_existing_outcome_metadata_preserved(self):
        """Execution stats written via update_operation_metadata survive a refresh."""
        ops = [_make_mock_op("op_001", "move_to_coordinate")]
        indexer, _ = _make_indexer(ops)

        store = VectorStore()
        store.add_operation("op_001", _unit(4), {"name": "move_to_coordinate"})
        store.update_operation_metadata("op_001", {
            "execution_count": 42,
            "last_outcome": "success",
        })

        # Now add all context docs so nothing new is embedded
        for ctx_id in CONTEXT_DOC_IDS:
            store.add_operation(ctx_id, _unit(4), {"name": ctx_id})

        indexer.refresh_index(store, save=False)

        # The original operation's metadata must be untouched
        op_entry = store.get_operation("op_001")
        assert op_entry is not None
        assert op_entry["metadata"]["execution_count"] == 42
        assert op_entry["metadata"]["last_outcome"] == "success"

    def test_new_op_does_not_affect_existing_metadata(self):
        """Adding a new operation must not change metadata of existing entries."""
        ops = [
            _make_mock_op("op_001", "move_to_coordinate"),
            _make_mock_op("op_002", "grasp_object"),
        ]
        indexer, _ = _make_indexer(ops)

        store = VectorStore()
        store.add_operation("op_001", _unit(4), {"name": "move_to_coordinate"})
        store.update_operation_metadata("op_001", {"execution_count": 7})
        for ctx_id in CONTEXT_DOC_IDS:
            store.add_operation(ctx_id, _unit(4), {"name": ctx_id})

        indexer.refresh_index(store, save=False)

        op_entry = store.get_operation("op_001")
        assert op_entry is not None
        assert op_entry["metadata"]["execution_count"] == 7


# ---------------------------------------------------------------------------
# Workflow handling
# ---------------------------------------------------------------------------

class TestRefreshIndexWorkflows:
    """refresh_index handles workflow patterns alongside operations."""

    def test_new_workflow_added(self):
        """A workflow not yet in the store is added on refresh."""
        ops = []
        workflows = [_make_mock_workflow("wf_001", "handoff_pattern")]
        indexer, _ = _make_indexer(ops, workflows)

        store = VectorStore()
        indexer.refresh_index(store, save=False)

        assert "wf_001" in store.operation_ids

    def test_existing_workflow_not_duplicated(self):
        """A workflow already in the store is not added again."""
        ops = []
        workflows = [_make_mock_workflow("wf_001", "handoff_pattern")]
        indexer, emb_gen = _make_indexer(ops, workflows)

        store = VectorStore()
        store.add_operation("wf_001", _unit(4), {"name": "handoff_pattern"})
        for ctx_id in CONTEXT_DOC_IDS:
            store.add_operation(ctx_id, _unit(4), {"name": ctx_id})

        indexer.refresh_index(store, save=False)

        assert store.operation_ids.count("wf_001") == 1
        emb_gen.generate_embeddings.assert_not_called()


if __name__ == "__main__":
    import pytest
    pytest.main([__file__, "-v"])
